**ÖRÜNTÜ TANIMA-NAİVE BAYES**

**KÜTÜPHANELERI IMPORT ETME**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import GaussianNB

**VERİ SETİ OKUMA**

In [2]:
dataset = pd.read_csv('heart_failure_clinical_records_dataset.csv')
df = dataset.copy()

**EXPLORATORY DATA ANALYSIS (EDA)**

In [3]:
df.shape #verinin toplam boyutu

(299, 13)

In [4]:
df.head(10) #veri setinin ilk 10 satırını göster

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   
5  90.0        1                        47         0                 40   
6  75.0        1                       246         0                 15   
7  60.0        1                       315         1                 60   
8  65.0        0                       157         0                 65   
9  80.0        1                       123         0                 35   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   
5                    1  204000.00               2.1           132    1   
6                    0  127000.00               1.2           137    1   
7                    0  454000.00               1.1           131    1   
8                    0  263358.03               1.5           138    0   
9                    1  388000.00               9.4           133    1   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1  
5        1     8            1  
6        0    10            1  
7        1    10            1  
8        0    10            1  
9        1    10            1

In [5]:
y=df['DEATH_EVENT']
X=df.drop(['DEATH_EVENT'],axis=1)

In [6]:
X.head() #girdileri gör

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  
0        0     4  
1        0     6  
2        1     7  
3        0     7  
4        0     8

In [7]:
y.head() #sonuç değişkeni (label)

0    1
1    1
2    1
3    1
4    1
Name: DEATH_EVENT, dtype: int64

In [8]:
#sınıf adetleri
y.value_counts(sort=False)

0    203
1     96
Name: DEATH_EVENT, dtype: int64

**TRAIN-TEST SPLIT**

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=60)

In [10]:
#boyutlar
X_train.shape, X_test.shape

((209, 12), (90, 12))

**MODEL GELİŞTİRME**

In [11]:
#Gaussian Naive Bayes kullanacağız
nb = GaussianNB() #nesne oluşturduk
nb_model = nb.fit(X_train, y_train) 
nb_model

GaussianNB()

**SONUÇ TAHMİNİ**

In [12]:
nb_model.predict(X_test)[0:20]

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
      dtype=int64)

In [13]:
nb_model.predict_proba(X_test)[0:20]

array([[0.79189813, 0.20810187],
       [0.42445969, 0.57554031],
       [0.65659586, 0.34340414],
       [0.59819409, 0.40180591],
       [0.99784123, 0.00215877],
       [0.34632478, 0.65367522],
       [0.99522298, 0.00477702],
       [0.04159856, 0.95840144],
       [0.73547635, 0.26452365],
       [0.06786173, 0.93213827],
       [0.1003917 , 0.8996083 ],
       [0.98233265, 0.01766735],
       [0.6678629 , 0.3321371 ],
       [0.99033393, 0.00966607],
       [0.36672819, 0.63327181],
       [0.95004991, 0.04995009],
       [0.99284584, 0.00715416],
       [0.78152805, 0.21847195],
       [0.99478833, 0.00521167],
       [0.98805435, 0.01194565]])

In [14]:
from sklearn.metrics import accuracy_score
y_pred = nb_model.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0], dtype=int64)

**TAHMİN SONUCU ANALİZİ (ACCURACY SCORE)**

In [15]:
accuracy_score(y_test, y_pred)

0.8333333333333334